modules:

  enable::
    - tcl

  prefix_inspections::
    bin:
      - PATH
    bin64:
      - PATH
    share/man:
      - MANPATH
    man:
      - MANPATH
    lib:
      - LD_LIBRARY_PATH
    lib64:
      - LD_LIBRARY_PATH
    lib/pkgconfig:
      - PKG_CONFIG_PATH
    lib64/pkgconfig:
      - PKG_CONFIG_PATH
    '':
      - CMAKE_PREFIX_PATH

  tcl:
    verbose: True
    hash_length: 0
    whitelist:
      - arm-forge
      - blender
      - ccache
      - cli-tools
      - cmake
      - cuda
      - cudnn
      - darshan-runtime
      - darshan-util
      - doxygen
      - emacs
      - environment-modules
      - ffmpeg
      - gdb
      - git
      - graphviz
      - hpctoolkit
      - hpcviewer
      - hpe-mpi
      - intel-mpi
      - ispc
      - julia
      - llvm
      - mvapich2
      - nvhpc
      - pgi
      - python
      - snakemake
      - stat
      - valgrind
      - virtualgl
    blacklist:
      - '%gcc'
      - '%intel'
      - '%clang'
      - '%pgi'
    projections:
      all: '{name}/{version}'
    all:
      autoload: 'all'
      load_only_generated: true
      environment:
        set:
          '${PACKAGE}_ROOT': '${PREFIX}'
    gcc:
      environment:
        set:
          MPICC_CC: 'gcc'
          MPICXX_CXX: 'g++'
          MPIF90_F90: 'gfortran'
    intel-parallel-studio:
      environment:
        set:
          MPICC_CC: 'icc'
          MPICXX_CXX: 'icpc'
          MPIF90_F90: 'ifort'
    intel:
      environment:
        set:
          MPICC_CC: 'icc'
          MPICXX_CXX: 'icpc'
          MPIF90_F90: 'ifort'
    pgi:
      environment:
        set:
          MPICC_CC: 'pgcc'
          MPICXX_CXX: 'pgc++'
          MPIF90_F90: 'pgfortran'
    llvm:
      environment:
        set:
          MPICC_CC: 'clang'
          MPICXX_CXX: 'clang++'
          MPIF90_F90: 'gfortran'
    nvhpc:
      environment:
        set:
          MPICC_CC: 'nvc'
          MPICXX_CXX: 'nvc++'
          MPIF90_F90: 'nvfortran'
