modules:

  enable::
    - tcl

  prefix_inspections::
    bin:
      - PATH
    bin64:
      - PATH
    share/man:
      - MANPATH
    man:
      - MANPATH
    lib:
      - LD_LIBRARY_PATH
    lib64:
      - LD_LIBRARY_PATH
    lib/pkgconfig:
      - PKG_CONFIG_PATH
    lib64/pkgconfig:
      - PKG_CONFIG_PATH
    '':
      - CMAKE_PREFIX_PATH

  tcl:
    verbose: True
    hash_length: 0
    whitelist:
      - arm-forge
      - blender
      - cmake
      - cuda
      - cudnn
      - darshan-runtime
      - darshan-util
      - doxygen
      - emacs
      - environment-modules
      - ffmpeg
      - gdb
      - git
      - graphviz
      - hpctoolkit
      - hpcviewer
      - hpe-mpi
      - intel-mpi
      - ispc
      - julia
      - mvapich2
      - python
      - snakemake
      - stat
      - valgrind
      - virtualgl
    blacklist:
      - '%gcc'
      - '%intel'
      - '%clang'
      - '%pgi'
    naming_scheme: '${PACKAGE}/${VERSION}'
    all:
      autoload: 'all'
      suffixes:
        '~mpi': 'serial'
      environment:
        set:
          '${PACKAGE}_ROOT': '${PREFIX}'
