modules:

  enable::
    - tcl

  prefix_inspections::
    bin:
      - PATH
    bin64:
      - PATH
    share/man:
      - MANPATH
    man:
      - MANPATH
    lib:
      - LD_LIBRARY_PATH
    lib64:
      - LD_LIBRARY_PATH
    lib/pkgconfig:
      - PKG_CONFIG_PATH
    lib64/pkgconfig:
      - PKG_CONFIG_PATH
    '':
      - CMAKE_PREFIX_PATH

  tcl:
    verbose: True
    hash_length: 0
    whitelist:
      - boost
      - gmsh
      - hdf5~mpi
      - highfive~mpi
      - neuron
      - python-dev
      - 'tensorflow@1.12.0'
    blacklist:
      - '%gcc'
      - '%intel'
      - '%clang'
      - '%pgi'
    naming_scheme: '${PACKAGE}/${VERSION}'
    all:
      autoload: 'all'
      suffixes:
        '^python@:2.99': '/python2'
        '^python@3:': '/python3'
        '~mpi': '/serial'
      environment:
        set:
          '${PACKAGE}_ROOT': '${PREFIX}'
