spack:
  view: false
  modules:
    default:
      tcl:
        include:
          - brayns
          - py-bcsb
          - py-brayns
          - brion
          - meshball
          - ultraliser
  specs:
    - brayns
    - brayns@3.4.1
    - brayns@3.4.0
    - py-bcsb
    - py-bcsb@2.1.1
    - py-brayns
    - py-brayns@3.4.1
    - py-brayns@3.4.0
    - brion +python
    - ultraliser ^hdf5~mpi
