spack:
  view: false
  modules:
    default:
      tcl:
        include:
          - brayns
          - py-brayns
          - brion+python
          - meshball
          - ultraliser
  specs:
    - brayns
    - py-brayns
    - brion +python
   #- ultraliser ^hdf5~mpi
