spack:
  view: false
  modules:
    default:
      tcl:
        include:
          - brayns
          - py-bcsb
          - py-brayns
          - brion
          - meshball
          - ultraliser
  specs:
    - brayns
    - py-bcsb
    - py-bcsb@2.2.0
    - py-brayns
    - brion +python
    - ultraliser ^hdf5~mpi
