spack:
  view: false
  modules:
    default:
      tcl:
        include:
          # - py-amici  # BSD-276
          - py-atlannot
          - py-atldld
          - py-atlinter
          - py-bluecellulab
          - py-bluepyefe
          - py-bluepymm
          - py-bluepyopt
          - py-bluepyparallel
          - py-connectome-manipulator
          - py-multiscale-run
          - py-efel
          - py-emodel-generalisation
          - py-synthesis-workflow
          - py-visual-cortex-analysis
          - py-connectomeutilities
  packages:
    hdf5:
      variants: ~mpi+hl
    highfive:
      variants: ~mpi
    libsonata:
      variants: ~mpi
    py-h5py:
      variants: ~mpi
  specs:
    # - py-amici  # BSD-276
    - py-atlannot
    - py-atldld
    - py-atlinter
    - py-bluecellulab
    - py-bluepyefe
    - py-bluepymm
    - py-bluepyopt
    - py-bluepyparallel
    - py-connectome-manipulator+convert
    - py-efel
    - py-emodel-generalisation
    - py-multiscale-run
    - py-synthesis-workflow
    - py-visual-cortex-analysis
    - py-connectomeutilities
