spack:
  view: false
  modules:
    default:
      tcl:
        include:
          - py-amici  # BSD-276
          - py-atlannot
          - py-atldld
          - py-atlinter
          - py-bluecellulab
          - py-bluepyefe
          - py-bluepymm
          - py-bluepyopt
          - py-bluepyparallel
          - py-connectome-manipulator
          - py-multiscale-run
          - py-efel
          - py-synthesis-workflow
          - py-visual-cortex-analysis
  packages:
    hdf5:
      variants: ~mpi+hl
    highfive:
      variants: ~mpi
    libsonata:
      variants: ~mpi
    proj:
      variants: ~curl
    py-h5py:
      variants: ~mpi
    py-ipyparallel:
      # otherwise, 6.3 is picked (cheaper setuptools penalty), and things break
      require: "@8:"
    py-torch:
      require: "@1.13.1"
    vtk:
      require: "@:9.0.3"
  specs:
    - py-amici  # BSD-276
    - py-atlannot
    - py-atldld
    - py-atlinter
    - py-bluecellulab
    - py-bluepyefe
    - py-bluepymm
    - py-bluepyopt
    - py-bluepyparallel
    - py-connectome-manipulator+convert
    - py-efel
    - py-multiscale-run
    - py-synthesis-workflow
    - py-visual-cortex-analysis
