config:
  install_tree: $SOFTS_DIR_PATH
  source_cache: $SOFTS_DIR_PATH/.cache
  module_roots:
    tcl: $MODS_DIR_PATH/tcl
    lmod: $MODS_DIR_PATH/lmod
  build_stage:
    - $TMPDIR
    - $SOFTS_DIR_PATH/.stage
  install_path_scheme: '${ARCHITECTURE}/${COMPILERNAME}-${COMPILERVER}/${PACKAGE}-${VERSION}-${HASH:10}'
  build_jobs: 36
