spack:
  view: false
  concretization: separately
  packages:
    all:
      compiler: [gcc@9.3.0, intel]
      providers:
        mpi: [hpe-mpi@2.21]
        lapack: [intel-mkl@2019.3.199]
    python:
      version: [3.8.3]
  specs:
    - asciitoh5@1.0
    - brainbuilder
    - brayns@1.0.1%gcc +brion ^brion@3.1.0 ^ospray%intel
    - brayns-brainatlas@0.1.0%gcc ^brayns@0.8.0 ^ospray@1.7.3%intel
    - brayns-membranelessorganelles@0.1.0%gcc ^brayns@0.8.0 ^ospray@1.7.3%intel
    - brayns%gcc +opendeck +brion ^brion@3.1.0 ^ospray@1.7.3%intel
    - brayns-topologyviewer@0.1.0%gcc ^brayns@0.8.0 ^ospray@1.7.3%intel
    - brion@3.1.0 +python
    - brion@3.2.0 +python
    - brion@3.3.0 +python
    - brion@3.3.1 +python
    - circuit-build
    - connectome-tools@0.3.3
    - emsim ^brion@3.1.0
    - functionalizer@3.12.2
    - meshball ^brion@3.1.0
    - model-neocortex%intel
    - nest@2.18.0
    - nest@2.20.0
    - neurodamus-core~common%intel
    - neurodamus-core+common
    - neurodamus-hippocampus+coreneuron%intel
    - neurodamus-hippocampus+coreneuron%intel^coreneuron+knl
    - neurodamus-mousify+coreneuron%intel
    - neurodamus-neocortex+coreneuron%intel
    - neurodamus-neocortex+coreneuron%intel^coreneuron+knl
    - neurodamus-thalamus+coreneuron%intel
    - neurodamus-thalamus+coreneuron%intel^coreneuron+knl
    - parquet-converters
    - placement-algorithm
    - psp-validation
    - py-basalt@0.2.9
    - py-bbp-analysis-framework
    - py-bbp-workflow
    - py-bglibpy%gcc ^neuron%intel
    - py-bluepy
    - py-bluepyefe
    - py-bluepymm%gcc ^neuron%intel
    - py-bluepyopt%gcc ^neuron%intel
    - py-bluepysnap
    - py-currentscape
    - py-efel
    - py-entity-management
    - py-minis-validation
    - py-morphio
    - py-morphology-repair-workflow
    - py-morph-tool
    - py-neurodamus
    - py-notebook
    - py-pytouchreader
    - py-simwriter
    - py-sonata-network-reduction%gcc ^neuron%intel^py-ipython%gcc
    - regiodesics
    - reportinglib%intel
    - spatial-index
    - spykfunc
    - steps@3.5.0b+petsc
    - synapsetool
    - touchdetector
    - ultraliser
    # - zee
