spack:
  view: false
  concretization: separately
  modules:
    tcl:
      whitelist:
        - boost
        - gmsh
        - hdf5+mpi%gcc
        - highfive+mpi%gcc
        - neuron+mpi~debug%intel
        - omega-h
        - petsc+int64+mpi
        - py-cgal-pybind
        - py-dask-mpi
        - py-flake8
        - py-mpi4py%gcc
        - python-dev
        - py-h5py+mpi%gcc
        - py-notebook
        - py-numpy%gcc
        - py-poisson-recon-pybind
        - py-rtree
        - py-scikit-learn
        - py-tensorflow
        - py-virtualenv
      projections:
        all: '{name}/{version}'
        'omega-h+gmsh': '{name}/{version}-gmsh'
  packages:
    trilinos:
      version: [xsdk-0.4.0-rc1]
  specs:
    - matrix:
        - [
            coreneuron,
            coreneuron build_type=Debug,
            hdf5+mpi,
            highfive+mpi,
            neuron,
            neuron+debug,
            python,
            py-h5py,
            py-mpi4py,
            py-numpy,
            py-pandas
          ]
        - ['%gcc', '%intel']
    - assimp
    - boost+python@1.70.0
    - boost+python@1.73.0
    - caliper+cuda cuda_arch=70
    - catch2
    - deflect
    - easyloggingpp
    - eigen
    - fmt
    - gmsh+metis+mpi+oce+openmp+shared
    - hdf5~mpi
    - highfive~mpi
    - hypre+int64+mpi
    - libarchive
    - libxml2
    - metis+int64
    - morphio
    - morpho-kit
    - mvdtool+mpi
    - neuron+mpi~debug%intel
    - neuron+coreneuron+debug~legacy-unit+tests%nvhpc ^coreneuron+gpu~legacy-unit~report+tests ^py-cython%gcc ^py-numpy%gcc
    - nlohmann-json +single_header
    - omega-h+trilinos
    - omega-h+gmsh+trilinos
    - openscenegraph build_type=Release
    - parmetis
    - petsc~int64+mpi
    - petsc+int64+mpi
    - py-argcomplete
    - py-argparse
    - py-aspy-yaml
    - py-babel
    - py-beautifulsoup4
    - py-breathe
    - py-cached-property
    - py-cffi
    - py-cfgv
    - py-cgal-pybind
    - py-click
    - py-clustershell
    - py-cmake-format
    - py-configparser
    - py-contextlib2
    - py-coverage
    - py-cycler
    - py-cython
    - py-dask-mpi
    - py-dateutil
    - py-deap
    - py-decorator
    - py-docopt
    - py-exhale
    - py-flake8
    - py-funcsigs
    - py-future
    - py-hdfs
    - py-humanize
    - py-identify
    - py-importlib-metadata
    - py-importlib-resources
    - py-ipykernel
    - py-ipyparallel
    - py-ipywidgets
    - py-jinja2
    - py-jprops
    - py-lazy-property
    - py-line-profiler
    - py-linecache2
    - py-lxml
    - py-markdown
    - py-matplotlib
    - py-morphio
    - py-morpho-kit
    - py-munkres
    - py-mvdtool~mpi
    - py-neurom
    - py-nodeenv
    - py-notebook
    - py-pathlib2
    - py-pbr
    - py-pillow
    - py-pip
    - py-plotly
    - py-ply
    - py-poisson-recon-pybind
    - py-pre-commit
    - py-progress
    - py-py4j
    - py-pyarrow+parquet
    - py-pylru
    - py-pyspark
    - py-pytest
    - py-pyyaml
    - py-regex
    - py-requests
    - py-rtree
    - py-scikit-learn
    - py-scipy
    - py-seaborn
    - py-setuptools
    - py-setuptools-scm
    - py-simplejson
    - py-six
    - py-sphinx
    - py-sphinx-rtd-theme
    - py-sympy
    - py-tensorflow@2.4.2
    - python-dev
    - py-toml
    - py-traceback2
    - py-unittest2
    - py-urllib3
    - py-virtualenv
    - py-virtualenv-clone
    - py-virtualenvwrapper
    - py-wheel
    - py-zipp
    - random123
    - range-v3
    - rockets
    - rocksdb~static
    - spark
    - sundials+int64
    - superlu-dist@5.4.0
    - synapsetool
