spack:
  view: false
  concretization: separately
  packages:
    all:
      compiler: [gcc@9.3.0, intel]
      providers:
        mpi: [hpe-mpi@2.21]
        lapack: [intel-mkl@2019.3.199]
    python:
      version: [3.8.3]
  specs:
    - archngv@0.0.0
    - asciitoh5@1.0
    - brainbuilder@0.14.0
    - brayns@1.0.1%gcc +brion ^brion@3.1.0 ^ospray%intel
    - brayns-brainatlas@0.1.0%gcc ^brayns@0.8.0 ^ospray@1.7.3%intel
    - brayns%gcc +opendeck +brion ^brion@3.1.0 ^ospray@1.7.3%intel
    - brayns-membranelessorganelles@0.1.0%gcc ^brayns@0.8.0 ^ospray@1.7.3%intel
    - brayns-topologyviewer@0.1.0%gcc ^brayns@0.8.0 ^ospray@1.7.3%intel
    - brion@3.1.0 +python
    - brion@3.2.0 +python
    - connectome-tools@0.3.2
    - emsim ^brion@3.1.0
    - functionalizer@3.12.2
    - meshball ^brion@3.1.0
    - model-neocortex%intel
    - nest@2.18.0
    - nest@2.20.0
    - neurodamus-core+common@2.11.1
    - neurodamus-core~common@2.11.1%intel
    - neurodamus-hippocampus+coreneuron@0.4%intel
    - neurodamus-hippocampus+coreneuron@0.4%intel^coreneuron+knl
    - neurodamus-mousify+coreneuron@0.3%intel
    - neurodamus-neocortex+coreneuron@0.3%intel
    - neurodamus-neocortex+coreneuron@0.3%intel^coreneuron+knl
    - neurodamus-thalamus+coreneuron@0.3%intel
    - neurodamus-thalamus+coreneuron@0.3%intel^coreneuron+knl
    - parquet-converters@0.5.7
    - placement-algorithm@2.1.0
    - psp-validation@0.3.1
    - py-basalt@0.2.9
    - py-bbp-analysis-framework@1.6.42
    - py-bglibpy@4.2.23%gcc ^neuron%intel
    - py-bluepy@0.14.8
    - py-bluepymm@0.7.49%gcc ^neuron%intel
    - py-bluepyopt@1.9.27%gcc ^neuron%intel
    - py-bluepysnap@0.6.1
    - py-efel@3.0.80
    - py-entity-management@1.2.2
    - py-jupyter-notebook@4.2.3
    - py-morphio@2.3.4
    - py-morphology-repair-workflow@1.0.4
    - py-morph-tool@0.2.5
    - py-neurodamus@1.3.1
    - py-pytouchreader@1.4.6
    - py-simwriter@1.0.1
    - py-sonata-network-reduction@0.0.10%gcc ^neuron%intel^py-ipython%gcc
    - regiodesics@0.1.2
    - reportinglib%intel
    - spatial-index@0.2.1
    - spykfunc@0.15.7
    - steps@3.5.0b+petsc
    - synapsetool@0.6.0
    - touchdetector@5.4.0
    - ultraliser
    # - zee@develop
