spack:
  view: false
  concretization: separately
  packages:
    all:
      compiler: [gcc@4.8.5]
    intel-parallel-studio:
      variants: +advisor+clck+daal+gdb+inspector+ipp+itac+mkl+mpi+rpath+shared+tbb+vtune
  specs:
    - gcc@9.3.0
    - gcc@10.1.0
    - intel@20.0.1
    - llvm@10.0.0%gcc@9.3.0
    # - intel-parallel-studio@cluster.2020.1
    - pgi+network+nvidia+mpi@19.10
