spack:
  view: false
  concretization: separately
  packages:
    all:
      compiler: [gcc@9.3.0]
      providers:
        jpeg: [libjpeg-turbo]
        mpi: [hpe-mpi]
        lapack: [intel-mkl]
    cairo:
      variants: +pdf+png
    graphviz:
      variants: +pangocairo
    mvapich2:
      variants: fabrics=mrail process_managers=slurm file_systems=gpfs
    pgi:
      variants: +network+nvidia+mpi
    python:
      version: [3.8.3]
    timemory:
      variants: +mpi~cuda~cupti+caliper~gperftools~python
  specs:
    - llvm@11.0.0 +python
    - nvhpc@20.9 install_type=network
    - arm-forge@20.2.0-Redhat-7.0-x86_64
    - blender
    - boost~mpi@1.73.0
    - bzip2
    - ccache
    - cgal
    - cli-tools
    - cmake@3.15.7
    - cuda@10.1.243
    - cuda@11.1.0
    - cudnn@7.3.0.29-9.0-linux-x64
    - darshan-runtime
    - darshan-util
    - doxygen
    - emacs
    - environment-modules@4.5.1
    - ffmpeg
    - gdb~python
    - git
    - glew
    - gmsh+metis~mpi+oce+openmp+shared@4.4.1
    - graphviz
    - hdf5~mpi@1.10.7
    - help2man
    - hpctoolkit@2020.03.01
    - hpcviewer
    - hpe-mpi@2.22.hmpt
    - intel-mkl
    - intel-mpi
    - ispc@1.12.0
    - julia
    - libxslt
    - libzmq+libsodium%intel
    - mvapich2@2.3
    - ncurses
    - ninja
    - openblas
    - optix
    - python
    - qhull@2015.2
    - qt@5.14.2
    - readline
    - snakemake
    - sqlite
    - stat@4.0.2.999
    - symengine@0.3.0
    - timemory
    - valgrind~mpi
    - virtualgl
    - vrpn
    - zlib
