spack:
  view: false
  concretization: separately
  modules:
    tcl:
      whitelist:
        - arm-forge
        - bison
        - blender
        - ccache
        - cli-tools
        - cmake
        - cuda
        - cudnn
        - darshan-runtime
        - darshan-util
        - doxygen
        - environment-modules
        - flex
        - ffmpeg
        - gdb
        - git
        - graphviz
        - hpctoolkit
        - hpcviewer
        - hpe-mpi
        - intel-mpi
        - ispc
        - julia
        - llvm
        - mvapich2
        - ninja
        - nvhpc
        - pgi
        - python
        - snakemake
        - stat
        - totalview
        - valgrind
        - virtualgl
        - freeimage
        - ilmbase
        - openexr
  packages:
    all:
      compiler: [gcc@9.3.0]
      providers:
        jpeg: [libjpeg-turbo]
        mpi: [hpe-mpi]
        lapack: [intel-mkl]
    cairo:
      variants: +pdf+png
    graphviz:
      variants: +pangocairo+expat
    mvapich2:
      variants: fabrics=mrail process_managers=slurm file_systems=gpfs
    pgi:
      variants: +network+nvidia+mpi
    python:
      version: [3.8.3]
    timemory:
      variants: +mpi~cuda~cupti+caliper~gperftools~python
  specs:
    - llvm@12.0.0 +cuda cuda_arch=70 +omp_tsan +python ^cuda@11.0.2
    - nvhpc@21.2 install_type=network
    - nvhpc@21.9
    - arm-forge@20.2.0-Redhat-7.0-x86_64
    - bison
    - blender
    - boost~mpi@1.73.0
    - bzip2
    - ccache
    - cgal
    - cli-tools
    - cmake@3.15.7
    - cuda@11.0.2
    - cuda@11.4.2
    - cudnn@8.0.3.33-11.0-linux-x64
    - darshan-runtime
    - darshan-util
    - doxygen
    - environment-modules@4.5.1
    - ffmpeg
    - flex
    - freetype
    - gdb~python
    - git
    - glew
    - gmsh+metis~mpi+oce+openmp+shared
    - graphviz
    - hdf5~mpi@1.10.7
    - help2man
    - hpctoolkit@2020.03.01
    - hpcviewer
    - hpe-mpi@2.25.hmpt
    - intel-mkl
    - intel-mpi
    - ispc@1.12.0
    - julia
    - libxslt
    - libzmq+libsodium%intel
    - mvapich2@2.3
    - ncurses
    - ninja
    - openblas
    - optix
    - poppler
    - python
    - qhull@2015.2
    - qt@5.14.2
    - readline
    - snakemake
    - sqlite
    - stat@4.0.2.999
    - symengine@0.3.0
    - timemory
    - totalview
    - valgrind~mpi
    - virtualgl
    - vrpn
    - zlib
    # Viz needs; FreeImage should be axed ASAP
    - freeimage
    - ilmbase
    - openexr
