# Package configurations for BBP Software Stack

axis:
  - architecture
  - compiler
  - mpi
  - lapack
  - python

combinations: !include packages/toolchains.yaml

packages:

  #### circuit building ####

  gnu-stable-serial:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
      - python
    specs:
      - brainbuilder@0.11.1
      - connectome-tools@0.3.2
      - spykfunc@0.14.1
      - psp-validation@0.1.12
      - py-pytouchreader@1.4.3
      - py-basalt@0.2.4

  gnu-stable-parallel:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
      - mpi
    specs:
      - functionalizer@3.12.1
      - parquet-converters@0.4.1
      - synapsetool@0.4.1
      - touchdetector@4.4.2
      - brayns@0.8.0 +opendeck +brion ^brion+python

  gnu-stable-parallel-python:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
      - mpi
      #- python
    specs:
      - placement-algorithm@2.0.8

  #### sub-cellular ####

  gnu-stable-lapack-python-parallel:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
      - lapack
      - mpi
      - python
    specs:
      - steps@3.4.1+petsc

  gnu-stable-lapack-parallel:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
      - mpi
      - lapack
      #- python
    specs:
      - zee@develop

  gnu-stable-lapack-python:
    target_matrix:
      - gnu-stable
      - gnu-stable-py2
    requires:
      - architecture
      - compiler
      # - lapack
      - python
    specs:
      - py-bluepymm@0.6.38 ^neuron~mpi
      - py-bluepyopt@1.6.56 ^neuron~mpi
      - py-efel@3.0.22
      - py-bglibpy ^neuron~mpi


  #### cellular ####

  gnu-stable:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
    specs:
      - neurodamus-core+common

  intel-stable-parallel:
    target_matrix:
      - intel-stable
    requires:
      - architecture
      - compiler
      - mpi
    specs:
      - reportinglib

  intel-stable-python-parallel:
    target_matrix:
      - intel-stable
    requires:
      - architecture
      - compiler
      - mpi
      - python
    specs:
      - neurodamus-neocortex
      - neurodamus-hippocampus
      - neurodamus-thalamus
      - neurodamus-mousify
      - neurodamus-neocortex+coreneuron^coreneuron+knl
      - neurodamus-thalamus+coreneuron^coreneuron+knl
      - neurodamus-hippocampus+coreneuron^coreneuron+knl
