# Package configurations for BBP Software Stack

axis:
  - architecture
  - compiler
  - mpi
  - lapack
  - python

combinations: !include packages/toolchains.yaml

packages:

  #### circuit building ####

  gnu-stable-serial:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
      - python
    specs:
      - archngv@0.0.0
      - asciitoh5@1.0
      - brainbuilder@0.13.1
      - brion@3.1.0 +python
      - brion@3.2.0 +python
      - connectome-tools@0.3.2
      - spatial-index@0.2.1
      - spykfunc@0.15.6 ^spark@3.0.0 ^py-pyspark@3.0.0 ^openjdk@11:11.999
      - psp-validation@0.3.0
      - py-pytouchreader@1.4.6
      - py-basalt@0.2.9
      - py-entity-management@1.1.3
      - py-jupyter-notebook@4.2.3
      - py-bbp-analysis-framework@1.6.42
      - py-morphology-repair-workflow@1.0.4
      - py-simwriter@1.0.1
      - py-morph-tool@0.2.5
      - py-morphio@2.3.4
      - py-neurodamus
      - py-sonata-network-reduction@0.0.9 ^neuron%intel@19.0.4^py-ipython%gcc

  gnu-stable-serial-ophiophob:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
    specs:
      - emsim ^brion@3.1.0
      - meshball ^brion@3.1.0
      - regiodesics@0.1.2

  gnu-stable-parallel:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
      - mpi
    specs:
      - functionalizer@3.12.2
      - parquet-converters@0.5.5
      - synapsetool@0.6.0
      - touchdetector@5.4.0
      - brayns +opendeck +brion ^brion@3.1.0 ^ospray@1.7.3%intel@19.0.4
      - brayns@1.0.1 +brion ^brion@3.1.0 ^ospray%intel@19.0.4
      - brayns-topologyviewer@0.1.0 ^brayns@0.8.0 ^ospray@1.7.3%intel@19.0.4
      - brayns-brainatlas@0.1.0 ^brayns@0.8.0 ^ospray@1.7.3%intel@19.0.4
      - brayns-membranelessorganelles@0.1.0 ^brayns@0.8.0 ^ospray@1.7.3%intel@19.0.4

  gnu-stable-parallel-python:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
      - mpi
      #- python
    specs:
      - placement-algorithm@2.1.0

  #### sub-cellular ####

  gnu-stable-lapack-python-parallel:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
      - lapack
      - mpi
      - python
    specs:
      - steps@3.5.0b+petsc
      - nest@2.20.0

  gnu-stable-lapack-parallel:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
      - mpi
      - lapack
      #- python
    specs:
      - zee@develop

  gnu-stable-lapack-python:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
      # - lapack
      - python
    specs:
      - nest@2.18.0
      - py-efel@3.0.80
      - py-bglibpy@4.2.23 ^neuron%intel@19.0.4
      - py-bluepy@0.14.8
      - py-bluepymm@0.7.15 ^neuron%intel@19.0.4
      - py-bluepyopt@1.9.27 ^neuron%intel@19.0.4

  #### cellular ####

  gnu-stable:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
    specs:
      - neurodamus-core+common@2.11.1
      - ultraliser

  intel-stable:
    target_matrix:
      - intel-stable
    requires:
      - architecture
      - compiler
    specs:
      - model-neocortex

  intel-stable-parallel:
    target_matrix:
      - intel-stable
    requires:
      - architecture
      - compiler
      - mpi
    specs:
      - reportinglib

  intel-stable-python-parallel:
    target_matrix:
      - intel-stable
    requires:
      - architecture
      - compiler
      - mpi
      - python
    specs:
      - neurodamus-core~common@2.11.1
      - neurodamus-neocortex+coreneuron@0.3
      - neurodamus-hippocampus+coreneuron@0.4
      - neurodamus-thalamus+coreneuron@0.3
      - neurodamus-mousify+coreneuron@0.3
      - neurodamus-neocortex+coreneuron@0.3^coreneuron+knl
      - neurodamus-hippocampus+coreneuron@0.4^coreneuron+knl
      - neurodamus-thalamus+coreneuron@0.3^coreneuron+knl
