# Package configurations for BBP Software Stack

axis:
  - architecture
  - compiler
  - mpi
  - lapack
  - python

combinations: !include packages/toolchains.yaml

packages:

  #### circuit building ####

  gnu-stable-serial:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
      - python
    specs:
      - archngv@0.0.0
      - asciitoh5@1.0
      - brainbuilder@0.11.3
      - brainbuilder@0.11.4
      - connectome-tools@0.3.2
      - spatial-index@0.1.0
      - spykfunc@0.14.3
      - psp-validation@0.1.12
      - py-pytouchreader@1.4.3
      - py-basalt@0.2.4
      - py-entity-management@1.0.9
      - py-jupyter-notebook@4.2.3
      - brion@3.0.0 +python

  gnu-stable-outdated:
    target_matrix:
      - gnu-stable-py2
    requires:
      - architecture
      - compiler
      - python
    specs:
      - py-bbp-analysis-framework@0.6.39
      - py-simwriter@0.4.3
      - py-entity-management@1.0.9

  gnu-stable-parallel:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
      - mpi
    specs:
      - functionalizer@3.12.2
      - parquet-converters@0.4.1
      - synapsetool@0.4.1
      - touchdetector@4.4.2
      - touchdetector@5.0.1
      - touchdetector@5.1.0
      - brayns@0.8.0 +opendeck +brion ^ospray@1.7.3
      - brayns-topologyviewer@0.1.0 ^brayns@0.8.0 ^ospray@1.7.3
      - brayns-brainatlas@0.1.0  ^brayns@0.8.0 ^ospray@1.7.3
      - brayns-membranelessorganelles@0.1.0 ^brayns@0.8.0 ^ospray@1.7.3
  gnu-stable-parallel-python:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
      - mpi
      #- python
    specs:
      - placement-algorithm@2.0.8

  #### sub-cellular ####

  gnu-stable-lapack-python-parallel:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
      - lapack
      - mpi
      - python
    specs:
      - steps@3.4.1+petsc

  gnu-stable-lapack-parallel:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
      - mpi
      - lapack
      #- python
    specs:
      - zee@develop

  gnu-stable-lapack-python:
    target_matrix:
      - gnu-stable
      - gnu-stable-py2
    requires:
      - architecture
      - compiler
      # - lapack
      - python
    specs:
      - py-bluepy
      - py-bluepymm@0.6.38 ^neuron~mpi
      - py-bluepyopt@1.6.56 ^neuron~mpi
      - py-efel@3.0.22
      - py-bglibpy@4.1.4 ^neuron~mpi


  #### cellular ####

  gnu-stable:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
    specs:
      - neurodamus-core+common@2.5.0

  intel-stable-parallel:
    target_matrix:
      - intel-stable
    requires:
      - architecture
      - compiler
      - mpi
    specs:
      - reportinglib

  intel-stable-python-parallel:
    target_matrix:
      - intel-stable
    requires:
      - architecture
      - compiler
      - mpi
      - python
    specs:
      - neurodamus-neocortex+coreneuron@0.2
      - neurodamus-hippocampus+coreneuron@0.3
      - neurodamus-thalamus+coreneuron@0.2
      - neurodamus-mousify+coreneuron@0.2
      - neurodamus-neocortex+coreneuron@0.2^coreneuron+knl
      - neurodamus-thalamus+coreneuron@0.2^coreneuron+knl
      - neurodamus-hippocampus+coreneuron@0.3^coreneuron+knl
