# Package configurations for BBP Software Stack

axis:
  - architecture
  - compiler
  - mpi
  - lapack
  - python

combinations: !include packages/toolchains.yaml

packages:

  #### circuit building ####

  gnu-stable-serial:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
      - python
    specs:
      - archngv@0.0.0
      - asciitoh5@1.0
      - brainbuilder@0.14.0
      - brion@3.1.0 +python
      - brion@3.2.0 +python
      - brion@3.3.0 +python
      - circuit-build@3.1.1
      - connectome-tools@0.3.3
      - spatial-index@0.2.1
      - spykfunc@0.15.7
      - psp-validation@0.3.1
      - py-pytouchreader@1.4.6
      - py-basalt@0.2.9
      - py-entity-management@1.2.2
      - py-jupyter-notebook@4.2.3
      - py-bbp-analysis-framework@1.6.42
      - py-bluepysnap@0.6.1
      - py-morphology-repair-workflow@1.0.4
      - py-simwriter@1.0.1
      - py-morph-tool@0.2.5
      - py-morphio@2.3.4
      - py-neurodamus@2.1.1
      - py-sonata-network-reduction@0.1.0 ^neuron%intel@19.0.4^py-ipython%gcc

  gnu-stable-serial-ophiophob:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
    specs:
      - emsim ^brion@3.1.0
      - meshball ^brion@3.1.0
      - regiodesics@0.1.2

  gnu-stable-parallel:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
      - mpi
    specs:
      - functionalizer@3.12.2
      - parquet-converters@0.5.7
      - synapsetool@0.6.1
      - touchdetector@5.5.0
      - brayns +opendeck +brion ^brion@3.1.0 ^ospray@1.7.3%intel@19.0.4
      - brayns@1.0.1 +brion ^brion@3.1.0 ^ospray%intel@19.0.4
      - brayns-topologyviewer@0.1.0 ^brayns@0.8.0 ^ospray@1.7.3%intel@19.0.4
      - brayns-brainatlas@0.1.0 ^brayns@0.8.0 ^ospray@1.7.3%intel@19.0.4
      - brayns-membranelessorganelles@0.1.0 ^brayns@0.8.0 ^ospray@1.7.3%intel@19.0.4

  gnu-stable-parallel-python:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
      - mpi
      #- python
    specs:
      - placement-algorithm@2.1.0

  #### sub-cellular ####

  gnu-stable-lapack-python-parallel:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
      - lapack
      - mpi
      - python
    specs:
      - steps@3.5.0b+petsc
      - nest@2.20.0

  gnu-stable-lapack-parallel:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
      - mpi
      - lapack
      #- python
    specs:
      - zee@develop

  gnu-stable-lapack-python:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
      # - lapack
      - python
    specs:
      - nest@2.18.0
      - py-efel@3.0.80
      - py-bluepyefe@0.3.13
      - py-bglibpy@4.4.10 ^neuron%intel@19.0.4
      - py-bluepy@0.14.14
      - py-bluepymm@0.7.49 ^neuron%intel@19.0.4
      - py-bluepyopt@1.9.27 ^neuron%intel@19.0.4
      - py-currentscape@0.0.2

  #### cellular ####

  gnu-stable:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
    specs:
      - neurodamus-core+common
      - ultraliser

  intel-stable:
    target_matrix:
      - intel-stable
    requires:
      - architecture
      - compiler
    specs:
      - model-neocortex@1.1

  intel-stable-parallel:
    target_matrix:
      - intel-stable
    requires:
      - architecture
      - compiler
      - mpi
    specs:
      - reportinglib

  intel-stable-python-parallel:
    target_matrix:
      - intel-stable
    requires:
      - architecture
      - compiler
      - mpi
      - python
    specs:
      - neurodamus-core@3.0.2~common
      - neurodamus-neocortex@1.1-3.0.2+coreneuron
      - neurodamus-hippocampus@1.1-3.0.2+coreneuron
      - neurodamus-thalamus@1.1-3.0.2+coreneuron
      - neurodamus-mousify@1.1-3.0.2+coreneuron
      - neurodamus-neocortex@1.1-3.0.2+coreneuron^coreneuron+knl
      - neurodamus-hippocampus@1.1-3.0.2+coreneuron^coreneuron+knl
      - neurodamus-thalamus@1.1-3.0.2+coreneuron^coreneuron+knl
