# Package configurations for BBP Software Stack

axis:
  - architecture
  - compiler
  - mpi
  - lapack
  - python

combinations: !include packages/toolchains.yaml

packages:

  #### circuit building ####

  gnu-stable-serial:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
      - python
    specs:
      - archngv@0.0.0
      - asciitoh5@1.0
      - brainbuilder@0.11.3
      - brainbuilder@0.11.4
      - brainbuilder@0.11.5
      - brainbuilder@0.11.6
      - connectome-tools@0.3.2
      - spatial-index@0.1.0
      - spykfunc@0.15.2
      - psp-validation@0.1.12
      - py-pytouchreader@1.4.3
      - py-basalt@0.2.4
      - py-entity-management@1.0.16
      - py-jupyter-notebook@4.2.3
      - brion@3.0.0 +python ^boost@1.65.0
      - py-bbp-analysis-framework@1.6.40
      - py-morph-tool@0.1.14

  gnu-stable-serial-ophiophob:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
    specs:
      - emsim
      - meshball

  gnu-stable-outdated:
    target_matrix:
      - gnu-stable-py2
    requires:
      - architecture
      - compiler
      - python
    specs:
      - py-bbp-analysis-framework@0.6.39
      - py-simwriter@0.4.3
      - py-entity-management@1.0.16

  gnu-stable-parallel:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
      - mpi
    specs:
      - functionalizer@3.12.2
      - parquet-converters@0.5.2
      - synapsetool@0.5.6
      - touchdetector@4.4.2
      - touchdetector@5.1.0
      - touchdetector@5.3.2
      - brayns +opendeck +brion ^ospray@1.7.3%intel
      - brayns@1.0.1 +brion ^ospray%intel
      - brayns@immersive +opendeck +brion +optix
      - brayns-topologyviewer@0.1.0 ^brayns@0.8.0 ^ospray@1.7.3%intel
      - brayns-brainatlas@0.1.0 ^brayns@0.8.0 ^ospray@1.7.3%intel
      - brayns-membranelessorganelles@0.1.0 ^brayns@0.8.0 ^ospray@1.7.3%intel

  gnu-stable-parallel-python:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
      - mpi
      #- python
    specs:
      - placement-algorithm@2.0.8

  #### sub-cellular ####

  gnu-stable-lapack-python-parallel:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
      - lapack
      - mpi
      - python
    specs:
      - steps@3.4.1+petsc
      - steps@3.5.0a+petsc
      - nest@2.18.0

  gnu-stable-lapack-parallel:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
      - mpi
      - lapack
      #- python
    specs:
      - zee@develop

  gnu-stable-lapack-python:
    target_matrix:
      - gnu-stable
      - gnu-stable-py2
    requires:
      - architecture
      - compiler
      # - lapack
      - python
    specs:
      - nest@2.18.0
      - py-bluepy
      - py-bluepymm@0.6.38
      - py-bluepyopt@1.6.56
      - py-efel@3.0.22
      - py-bglibpy@4.1.4


  #### cellular ####

  gnu-stable:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
    specs:
      - neurodamus-core+common@2.7.3
      - ultraliser

  intel-stable-parallel:
    target_matrix:
      - intel-stable
    requires:
      - architecture
      - compiler
      - mpi
    specs:
      - reportinglib

  intel-stable-python-parallel:
    target_matrix:
      - intel-stable
    requires:
      - architecture
      - compiler
      - mpi
      - python
    specs:
      - neurodamus-neocortex+coreneuron@0.3
      - neurodamus-hippocampus+coreneuron@0.4
      - neurodamus-thalamus+coreneuron@0.3
      - neurodamus-mousify+coreneuron@0.3
      - neurodamus-neocortex+coreneuron@0.3^coreneuron+knl
      - neurodamus-hippocampus+coreneuron@0.4^coreneuron+knl
      - neurodamus-thalamus+coreneuron@0.3^coreneuron+knl
