# Compiler Specs

# axis that defines software deployment strategy
axis:
  - architecture
  - compiler
  - mpi
  - lapack
  - python

# toolchain combinations
combinations:
  # core toolchain typically represent system compilers
  core:
    architecture:
    - linux-rhel7-x86_64
    compiler:
    - gcc@4.8.5
    mpi: None
    lapack: None
    python: None
  bootstrapped_core:
    architecture:
    - linux-rhel7-x86_64
    compiler:
    - gcc@8.3.0
    mpi: None
    lapack: None
    python: None

# list of compilers to build
packages:
  compilers:
    target_matrix:
      - core
    requires:
      - architecture
      - compiler
    specs:
      - gcc@9.3.0
      - gcc@8.3.0
      - intel-parallel-studio+advisor+clck+daal+gdb+inspector+ipp+itac+mkl+mpi+rpath+shared+tbb+vtune@cluster.2019.5
      #- intel@18.0.3
      - intel@19.0.4
      - pgi+network+nvidia+mpi@19.10
      - nvhpc@20.9 install_type=network

  bootstrapped_compilers:
    target_matrix:
      - bootstrapped_core
    requires:
      - architecture
      - compiler
    specs:
      - llvm@9.0.0
