# External libraries and packages

axis:
  - architecture
  - compiler
  - mpi
  - lapack
  - python

combinations: !include packages/toolchains.yaml

packages:

  gnu-stable-serial:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
    specs:
      - arrow+parquet~python@0.15.0
      - boost~mpi@1.70.0
      - bzip2@1.0.6
      - cuda@9.2.88
      - cuda@10.1.243
      - cudnn@7.3.0
      - freeimage@3.18.0
      - glew
      - gmsh+oce~mpi@3.0.6
      - hdf5~mpi@1.10.4
      - highfive~mpi@2.0
      - intel-mkl@2019.3.199
      - jdk@1.8.0_131-b11
      - julia
      - libjpeg
      - libjpeg-turbo
      - libxml2
      - libxslt
      - metis@5.1.0
      - ncurses
      - openblas@0.3.3
      - optix
      # - python@2.7.15
      - python@3.7.4
      - qhull@2015.2
      - qt@5.11.2 ^libjpeg-turbo
      - readline
      - snakemake
      - spark@2.4.0+hadoop
      - sqlite
      - symengine@0.3.0
      - vrpn
      - zeromq@4.2.5
      - zlib@1.2.11
