# External libraries and packages

axis:
  - architecture
  - compiler
  - mpi
  - lapack
  - python

combinations: !include packages/toolchains.yaml

packages:

  gnu-stable-serial:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
    specs:
      - boost~mpi@1.70.0
      - bzip2@1.0.6
      - cgal
      - cuda@9.0.176
      - cuda@9.2.88
      - cuda@10.1.243
      - cuda@11.1.0
      - cudnn@7.3.0
      # - freeimage@3.18.0
      - glew
      - gmsh+metis~mpi+oce+openmp+shared@4.4.1
      - hdf5~mpi@1.10.5
      - intel-mkl@2019.3.199
      - jdk@1.8.0_131-b11
      - julia
      - libjpeg
      - libjpeg-turbo
      - libxml2
      - libxslt
      - metis+int64@5.1.0
      - ncurses
      - ninja@1.8.2
      - openblas@0.3.3
      - optix
      - python@3.7.4
      - qhull@2015.2
      - qt@5.11.2 ^libjpeg-turbo
      - readline
      - snakemake
      - sqlite
      - symengine@0.3.0
      - timemory+mpi+cuda+cupti+caliper~gperftools~python@3.0.1
      - virtualgl
      - vrpn
      - zlib@1.2.11

  intel-stable-serial:
    target_matrix:
      - intel-stable
    requires:
      - architecture
      - compiler
    specs:
      - zeromq+libsodium@4.3.2
