# Common dependency packages

axis:
  - architecture
  - compiler
  - mpi
  - lapack
  - python

combinations: !include packages/toolchains.yaml

packages:

  gnu-stable-serial:
    target_matrix:
      - gnu-stable
    requires:
      - compiler
      - architecture
    specs:
      - arm-forge@19.0.4-linux-rhel7-x86_64
      - binutils@2.31.1
      - bison@3.0.5
      - blender
      - cmake@3.15.3
      - doxygen@1.8.15
      - emacs@26.1
      - environment-modules@3.2.10
      - ffmpeg
      - flex@2.6.3
      - gdb~python@8.2
      - gdbm@1.14.1
      - gettext@0.19.8.1
      - git@2.18.0
      - gmp@6.1.2
      - help2man@1.47.4
      - hpctoolkit
      - hpe-mpi@2.21
      - intel-mpi@2018.1.163
      - isl@0.18
      - ispc@1.10.0
      - libx11@1.6.5
      - m4@1.4.18
      - mpc@1.1.0
      - 'mvapich2@2.3 fabrics=mrail process_managers=slurm file_systems=gpfs'
      - ninja
      - node-js@6.12.2
      - npm@3.10.9
      - pkg-config@0.29.2
      - stat@develop
      - swig@3.0.12
      - tcl@8.6.8
      - texinfo@6.5
      - tk@8.6.8
      - util-macros@1.19.1
      - valgrind~mpi@3.15.0
