# Common dependency packages

axis:
  - architecture
  - compiler
  - mpi
  - lapack
  - python

combinations: !include packages/toolchains.yaml

packages:

  gnu-stable-serial:
    target_matrix:
      - gnu-stable
    requires:
      - compiler
      - architecture
    specs:
      - arm-forge@20.0.3-Redhat-7.0-x86_64
      - blender
      - cmake@3.15.3
      - darshan-runtime
      - darshan-util
      - doxygen@1.8.15
      - emacs@26.1
      - environment-modules@4.5.1
      - ffmpeg
      - gdb~python@8.2
      - git@2.18.0
      - graphviz@2.42.2
      - hpctoolkit@2019.08.14
      - hpcviewer@2020.05
      - hpe-mpi@2.21
      - intel-mpi@2018.1.163
      - ispc@1.10.0
      - 'mvapich2@2.3 fabrics=mrail process_managers=slurm file_systems=gpfs'
      - stat@develop
      - valgrind~mpi@3.15.0
