modules:

  enable::
    - tcl

  prefix_inspections::
    bin:
      - PATH
    bin64:
      - PATH
    share/man:
      - MANPATH
    man:
      - MANPATH
    lib:
      - LD_LIBRARY_PATH
    lib64:
      - LD_LIBRARY_PATH
    lib/pkgconfig:
      - PKG_CONFIG_PATH
    lib64/pkgconfig:
      - PKG_CONFIG_PATH
    '':
      - CMAKE_PREFIX_PATH

  tcl:
    verbose: True
    hash_length: 0
    whitelist:
      - allinea-forge@19.0.5
      - cmake
      - cuda
      - cudnn
      - doxygen
      - emacs
      - ffmpeg
      - hpctoolkit
      - hpe-mpi
      - ior
      - imb
      - intel-mpi
      - ispc
      - likwid
      - lmod
      - mvapich2
      - openmpi
      - osu-micro-benchmarks
      - stat
    blacklist:
      - '%gcc'
      - '%intel'
      - '%clang'
      - '%pgi'
    naming_scheme: '${PACKAGE}/${VERSION}'
    likwid@:4.3.1:
      environment:
        set:
          KMP_INIT_AT_FORK: 'FALSE'
    all:
      autoload: 'all'
      environment:
        set:
          '${PACKAGE}_ROOT': '${PREFIX}'
