modules:

  enable::
    - tcl

  prefix_inspections::
    bin:
      - PATH
    bin64:
      - PATH
    share/man:
      - MANPATH
    man:
      - MANPATH
    lib:
      - LD_LIBRARY_PATH
    lib64:
      - LD_LIBRARY_PATH
    lib/pkgconfig:
      - PKG_CONFIG_PATH
    lib64/pkgconfig:
      - PKG_CONFIG_PATH
    '':
      - CMAKE_PREFIX_PATH

  tcl:
    verbose: True
    hash_length: 0
    whitelist:
      - asciitoh5
      - brainbuilder
      - brayns
      - brayns-brainatlas
      - brayns-topologyviewer
      - brion+python
      - circuit-build
      - circuit-analysis
      - connectome-tools
      - emsim
      - functionalizer
      - meshball
      - model-neocortex
      - nest
      - neurodamus-core
      - neurodamus-hippocampus
      - neurodamus-neocortex
      - neurodamus-thalamus
      - neurodamus-mousify
      - parquet-converters
      - placement-algorithm
      - psp-validation
      - py-basalt
      - py-bbp-analysis-framework
      - py-bbp-workflow
      - py-bglibpy
      - py-bluepy
      - py-bluepymm
      - py-bluepyopt
      - py-bluepysnap
      - py-currentscape
      - py-efel
      - py-entity-management
      - py-notebook
      - py-minis-validation
      - py-morph-tool
      - py-morphio
      - py-morphology-repair-workflow
      - 'py-mvdtool%gcc'
      - py-neurodamus
      - py-simwriter
      - py-sonata-network-reduction
      - py-pytouchreader
      - regiodesics
      - reportinglib
      - spatial-index
      - spykfunc
      - 'synapsetool%gcc'
      - steps
      - touchdetector
      - ultraliser
    blacklist:
      - '%gcc'
      - '%intel'
      - '%clang'
      - '%pgi'
    projections:
      all: '{name}/{version}'
      ^coreneuron+knl: '{name}-knl/{version}'
      +common: '{name}/{version}-commonmods'
    all:
      autoload: 'all'
      load_only_generated: true
      environment:
        set:
          '${PACKAGE}_ROOT': '${PREFIX}'
    gcc:
      environment:
        set:
          MPICC_CC: 'gcc'
          MPICXX_CXX: 'g++'
          MPIF90_F90: 'gfortran'
    intel-parallel-studio:
      environment:
        set:
          MPICC_CC: 'icc'
          MPICXX_CXX: 'icpc'
          MPIF90_F90: 'ifort'
    intel:
      environment:
        set:
          MPICC_CC: 'icc'
          MPICXX_CXX: 'icpc'
          MPIF90_F90: 'ifort'
    pgi:
      environment:
        set:
          MPICC_CC: 'pgcc'
          MPICXX_CXX: 'pgc++'
          MPIF90_F90: 'pgfortran'
    llvm:
      environment:
        set:
          MPICC_CC: 'clang'
          MPICXX_CXX: 'clang++'
          MPIF90_F90: 'gfortran'
    nvhpc:
      environment:
        set:
          MPICC_CC: 'nvc'
          MPICXX_CXX: 'nvc++'
          MPIF90_F90: 'nvfortran'
