modules:

  enable::
    - tcl

  prefix_inspections::
    bin:
      - PATH
    bin64:
      - PATH
    share/man:
      - MANPATH
    man:
      - MANPATH
    lib:
      - LD_LIBRARY_PATH
    lib64:
      - LD_LIBRARY_PATH
    lib/pkgconfig:
      - PKG_CONFIG_PATH
    lib64/pkgconfig:
      - PKG_CONFIG_PATH
    '':
      - CMAKE_PREFIX_PATH

  tcl:
    verbose: True
    hash_length: 0
    whitelist:
      - archngv
      - asciitoh5
      - brainbuilder
      - brayns@0.8.0
      - brayns@immersive
      - brayns@1.0.1
      - brayns-brainatlas
      - brayns-graphs
      - brayns-topologyviewer
      - brion
      - connectome-tools
      - functionalizer
      - 'neurodamus%intel'
      - 'neurodamus-core+common'
      - neurodamus-hippocampus
      - neurodamus-neocortex
      - neurodamus-thalamus
      - neurodamus-mousify
      - neuron~debug+mpi
      - parquet-converters
      - placement-algorithm
      - psp-validation
      - py-basalt
      - py-bbp-analysis-framework
      - py-bglibpy
      - py-bluepy
      - py-bluepymm
      - py-bluepyopt
      - py-efel
      - py-entity-management
      - py-jupyter-notebook
      - py-simwriter
      - py-pytouchreader
      - reportinglib
      - spatial-index
      - spykfunc
      - 'synapsetool%gcc'
      - steps
      - touchdetector
      - ultraliser
    blacklist:
      - '%gcc'
      - '%intel'
      - '%clang'
      - '%pgi'
    naming_scheme: '${PACKAGE}/${VERSION}'
    all:
      autoload: 'all'
      suffixes:
        '^coreneuron+knl': 'knl'
        'neuron~mpi': 'serial'
      environment:
        set:
          '${PACKAGE}_ROOT': '${PREFIX}'
