config:
  install_tree: $SPACK_INSTALL_PREFIX/install
  source_cache: $SPACK_INSTALL_PREFIX/.cache
  module_roots:
    tcl: $SPACK_INSTALL_PREFIX/modules/tcl
  build_stage:
    - $SPACK_INSTALL_PREFIX/.stage
  install_path_scheme: '${ARCHITECTURE}/${COMPILERNAME}-${COMPILERVER}/${PACKAGE}-${VERSION}-${HASH:6}'
  build_jobs: 16
