config:
  db_lock_timeout: 120
  install_tree:
    root: $spack/opt/spack
    padded_length: 256
    projections:
      all: '{architecture}/{compiler.name}-{compiler.version}/{name}-{version}-{hash}'

