name: audit

on:
  workflow_call:
    inputs:
      with_coverage:
        required: true
        type: string
      python_version:
        required: true
        type: string

concurrency:
  group: audit-${{inputs.python_version}}-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}
  cancel-in-progress: true

jobs:
  # Run audits on all the packages in the built-in repository
  package-audits:
    runs-on: ${{ matrix.system.os }}
    strategy:
      matrix:
        system:
        - { os: windows-latest, shell: 'powershell Invoke-Expression -Command "./share/spack/qa/windows_test_setup.ps1"; {0}' }
        - { os: ubuntu-latest, shell: bash }
        - { os: macos-latest, shell: bash }
    defaults:
      run:
        shell: ${{ matrix.system.shell }}
    steps:
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
    - uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3
      with:
        python-version: ${{inputs.python_version}}
    - name: Install Python packages
      run: |
        pip install --upgrade pip setuptools pytest coverage[toml]
    - name: Setup for Windows run
      if: runner.os == 'Windows'
      run: |
        python -m pip install --upgrade pywin32
    - name: Package audits (with coverage)
      env:
          COVERAGE_FILE: coverage/.coverage-audits-${{ matrix.system.os }}
      if: ${{ inputs.with_coverage == 'true' && runner.os != 'Windows' }}
      run: |
          . share/spack/setup-env.sh
          coverage run $(which spack) audit packages
          coverage run $(which spack) audit configs
          coverage run $(which spack) -d audit externals
          coverage combine
    - name: Package audits (without coverage)
      if: ${{ inputs.with_coverage == 'false' && runner.os != 'Windows' }}
      run: |
          . share/spack/setup-env.sh
          spack -d audit packages
          spack -d audit configs
          spack -d audit externals
    - name: Package audits (without coverage)
      if: ${{ runner.os == 'Windows' }}
      run: |
          . share/spack/setup-env.sh
          spack -d audit packages
          ./share/spack/qa/validate_last_exit.ps1
          spack -d audit configs
          ./share/spack/qa/validate_last_exit.ps1
          spack -d audit externals
          ./share/spack/qa/validate_last_exit.ps1
    - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882
      if: ${{ inputs.with_coverage == 'true' && runner.os != 'Windows' }}
      with:
        name: coverage-audits-${{ matrix.system.os }}
        path: coverage
        include-hidden-files: true
