# These are nightly package tests for macOS
# focus areas:
# - initial user experience
# - scientific python stack
name: macOS builds nightly

on:
  schedule:
    # nightly at 1 AM
    - cron: '0 1 * * *'
  pull_request:
    branches:
    - develop
    paths:
      # Run if we modify this yaml file
      - '.github/workflows/macos_python.yml'
      # TODO: run if we touch any of the recipes involved in this

# GitHub Action Limits
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions

jobs:
  install_gcc:
    name: gcc with clang
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # @v2
    - uses: actions/setup-python@f38219332975fe8f9c04cca981d674bf22aea1d3 # @v2
      with:
        python-version: 3.9
    - name: spack install
      run: |
        . .github/workflows/install_spack.sh
        # 9.2.0 is the latest version on which we apply homebrew patch
        spack install -v --fail-fast gcc@9.2.0 %apple-clang

  install_jupyter_clang:
    name: jupyter
    runs-on: macos-latest
    timeout-minutes: 700
    steps:
    - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # @v2
    - uses: actions/setup-python@f38219332975fe8f9c04cca981d674bf22aea1d3 # @v2
      with:
        python-version: 3.9
    - name: spack install
      run: |
        . .github/workflows/install_spack.sh
        spack install -v --fail-fast py-jupyterlab %apple-clang

  install_scipy_clang:
    name: scipy, mpl, pd
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # @v2
    - uses: actions/setup-python@f38219332975fe8f9c04cca981d674bf22aea1d3 # @v2
      with:
        python-version: 3.9
    - name: spack install
      run: |
        . .github/workflows/install_spack.sh
        spack install -v --fail-fast py-scipy %apple-clang
        spack install -v --fail-fast py-matplotlib %apple-clang
        spack install -v --fail-fast py-pandas %apple-clang
