# These are nightly package tests for macOS
# focus areas:
# - initial user experience
# - scientific python stack
name: macOS builds nightly

on:
  schedule:
    # nightly at 1 AM
    - cron: '0 1 * * *'
  pull_request:
    branches:
    - develop
    paths:
      # Run if we modify this yaml file
      - '.github/workflows/macos_python.yml'
      # TODO: run if we touch any of the recipes involved in this

# GitHub Action Limits
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions

jobs:
  install_gcc:
    name: gcc with clang
    if: github.repository == 'spack/spack'
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # @v2
    - uses: actions/setup-python@d09bd5e6005b175076f227b13d9730d56e9dcfcb # @v2
      with:
        python-version: 3.9
    - name: spack install
      run: |
        . .github/workflows/install_spack.sh
        # 9.2.0 is the latest version on which we apply homebrew patch
        spack install -v --fail-fast gcc@11.2.0 %apple-clang

  install_jupyter_clang:
    name: jupyter
    if: github.repository == 'spack/spack'
    runs-on: macos-latest
    timeout-minutes: 700
    steps:
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # @v2
    - uses: actions/setup-python@d09bd5e6005b175076f227b13d9730d56e9dcfcb # @v2
      with:
        python-version: 3.9
    - name: spack install
      run: |
        . .github/workflows/install_spack.sh
        spack install -v --fail-fast py-jupyterlab %apple-clang

  install_scipy_clang:
    name: scipy, mpl, pd
    if: github.repository == 'spack/spack'
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # @v2
    - uses: actions/setup-python@d09bd5e6005b175076f227b13d9730d56e9dcfcb # @v2
      with:
        python-version: 3.9
    - name: spack install
      run: |
        . .github/workflows/install_spack.sh
        spack install -v --fail-fast py-scipy %apple-clang
        spack install -v --fail-fast py-matplotlib %apple-clang
        spack install -v --fail-fast py-pandas %apple-clang
