name: windows tests

on:
  push:
    branches:
      - features/windows-support
      - windows-ci
  pull_request:
    branches:
      - features/windows-support
      - windows-ci
defaults:
  run:
    shell:
     powershell Invoke-Expression -Command ".\share\spack\qa\windows_test_setup.ps1"; {0}
jobs:
  validate:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Python Packages
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade vermin
    - name: vermin (Spack's Core)
      run: vermin --backport argparse --backport typing -t='2.6-' -t='3.5-' -v spack/lib/spack/spack/ spack/lib/spack/llnl/ spack/bin/
    - name: vermin (Repositories)
      run: vermin --backport argparse --backport typing -t='2.6-' -t='3.5-' -v spack/var/spack/repos
  # Run style checks on the files that have been changed
  style:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip six setuptools flake8 isort>=4.3.5 mypy>=0.800 black pywin32 types-python-dateutil
    - name: Create local develop
      run: |
        .\spack\.github\workflows\setup_git.ps1
    - name: Run style tests
      run: |
        spack style
    - name: Verify license headers
      run: |
        python spack\bin\spack license verify
  unittest:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Python packages
      run: |
          python -m pip install --upgrade pip six pywin32 setuptools codecov coverage
    - name: Unit Test llnl
      run: |
        spack -h
        spack unit-test lib\spack\spack\test\llnl
    - name: Unit Test modules
      run: |
        spack unit-test lib\spack\spack\test\modules
    - name: Unit Test util
      run: |
        spack unit-test lib\spack\spack\test\util
    - name: Unit Test Common
      run: |
        spack unit-test lib\spack\spack\test\abi.py
        spack unit-test lib\spack\spack\test\architecture.py
        spack unit-test lib\spack\spack\test\url_fetch.py
        spack unit-test lib\spack\spack\test\url_parse.py
        spack unit-test lib\spack\spack\test\url_substitution.py
  unittest-cmd:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Python packages
      run: |
          python -m pip install --upgrade pip six pywin32 setuptools codecov coverage
    - name: Create local develop
      run: |
        .\spack\.github\workflows\setup_git.ps1
    - name: Unit Test Cmd
      run: |
        echo F|xcopy .\spack\share\spack\qa\configuration\windows_config.yaml $env:USERPROFILE\.spack\windows\config.yaml
        spack unit-test lib\spack\spack\test\cmd
  buildtest:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Python packages
      run: |
          python -m pip install --upgrade pip six pywin32 setuptools codecov coverage
    - name: Build Test
      run: |
        spack compiler find
        echo F|xcopy .\spack\share\spack\qa\configuration\windows_config.yaml $env:USERPROFILE\.spack\windows\config.yaml
        spack external find cmake
        spack install abseil-cpp
